### ISSUE TITLE
Stanza and Transformers NLP engines are superslow

### ISSUE THREAD

**Issue by edeak** [microsoft/presidio#1046]
**Describe the bug**
I'm running different analyzer containers with different NLP engines and models, but for this bug, we should only focus on the 3 engines:
- SpacyNlpEngine with default models
- StanzaNlpEngine with default models
- TransformersNlpEngine with default models

The fundamental issue is that Stanza and Transformers engines are both incredibly slow. Spacy processes smaller number of  documents almost instantly, while Stanza and Transformers take several _minutes_. I've set the logs to DEBUG to see what is going on, but didn't get any meaningful output. 

**To Reproduce**
1. Pull down my remote branch (**can't push a remote branch, how should I share my changes?**) and spin up the containers using `docker-compose-benchmark.yaml`.
2. Send analyze requests for the list of inputs taken from (this gist)[https://gist.github.com/edeak/f9bf2c6a8ddf26fb62e93b72f1abc06a]

**Expected behavior**
I'd expect the execution time to be approximately within the same scale.

**Screenshots**

**Additional context**
I was building the images and ran the tests on an M1 machine.

**Comment by omri374** [comment]
Hi @edeak. Stanza and transformers both used a PyTorch model under the hood, which has a different architecture than the spaCy one. These models in most cases are slower, especially on CPUs. spaCy made a comparison of different architectures with regards to words per second: https://spacy.io/usage/facts-figures#benchmarks-speed

Could you please validate that this is indeed the root cause and not something with Presidio? Will running the same text roughly take the same time directly on stanza/transformers? If yes, then this is a matter of the model architecture and not a bug or an issue with Presidio.

**Comment by edeak** [comment]
Hi @omri374, thanks for your response! I wasn't aware of that speed comparison table but my results are correlating with those values so I'm pretty sure that is the case and it's not something with presidio. I was also experiencing the same slowness with the `_trf` model but that was specifically called out on that model page so I was expecting that.

Based on your response I don't think this is a Presidio bug.
