### ISSUE TITLE
Analyzer is recognizing 'today'/'a moment' as date or date_time, how to rectify to precise date_times only?

### ISSUE THREAD

**Issue by himsgpt** [microsoft/presidio#1139]
[{'entity_type': 'DATE', 'score': 0.85, 'start': 80, 'entity': 'today'},   
{'entity_type': 'DATE_TIME', 'score': 0.85, 'start': 80, 'entity': 'today'},   
{'entity_type': 'DATE_TIME', 'score': 0.85, 'start': 1070, 'entity': 'a   moment'}]

I am invoking analyzer function using default parameters and it is predicting these 'today'/'a moment' as date or date_time, how to rectify this to precise date_times only?

**Comment by omri374** [comment]
Hi, this is probably because of how the underlying NER model detects these entities. There are several options here:
1. Replace the underlying model (see our [demo website](https://huggingface.co/spaces/presidio/presidio_demo) for some potential models, but any [huggingface/spacy/stanza](https://microsoft.github.io/presidio/analyzer/customizing_nlp_models/)/[flair](https://github.com/microsoft/presidio/blob/main/docs/samples/python/flair_recognizer.py) model could work)
2. Ignore the DATE_TIME output of the NER model, and use a different way to detect dates and times (for example, rule based and regex based).
