### ISSUE TITLE
BatchAnonymizer in Presidio takes longer to anonymize entities

### ISSUE THREAD

**Issue by rssurendran** [microsoft/presidio#1320]
I attempted to use BatchAnonymizer on a relatively modest database (Sakila.db) containing approximately 17 tables. Most tables have around 2,000 records, with a few exceptions where some tables have about 10,000 records. The anonymization process is taking a considerable amount of time. I experimented with implementing multithreading using ThreadPoolExecutors, but it did not result in any noticeable improvement in runtime. 

Are there alternative solutions to enhance the execution time?

**Comment by omri374** [comment]
A few suggestions:
1. Look into improving how spaCy does concurrent processing: https://spacy.io/api/language#pipe. For example, changing the `n_process` parameter could improve performance.
2. Look into `presidio-structured`. Instead of going cell by cell, it would first sample each column, and if PII is found in those samples, it would redact the entire column, making it a more efficient process.

**Comment by omri374** [comment]
Closing for now, please feel free to re-open if you require any more assistance.
