### ISSUE TITLE
Avoid: "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead."

### ISSUE THREAD

**Issue by ayelencasamassa** [microsoft/presidio#1366]
Greetings.
I am using presidio with k8s and I am getting:
"WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead."
How can fix that?

Images:
mcr.microsoft.com/presidio-analyzer:2.2.354
mcr.microsoft.com/presidio-anonymizer:2.2.354

Thanks!

**Comment by omri374** [comment]
@SharonHart @RoeyBC can you please provide your guidance?

**Comment by SharonHart** [comment]
The images we are standalone, so that they don't force or suggest a specific way of to host or deploy the application, as this should be up to the client depending on its needs. 
If you want to host a Flask application yourself, or in a IaaS platform like AKS, the recommendation is to use a WSGI server (such as uWSGI, Gunicorn), it can be on the same container. In that case, you can modify the Dockerfile CMD or ENTRYPOINT to work with WSGI. 
Deploying to a PaaS, like Azure App Service, for example, which is a sample we provide in the repo, do not require to maintain a WSGI server since it is built in the platform [Gunicorn is used](https://github.com/Azure-App-Service/python)
