### ISSUE TITLE
Usage Documentation

### ISSUE THREAD

**Issue by dante1119** [microsoft/presidio#236]
Is it possible to ask for a kind of quick start documentation to help the use of presidio from a User perspective? 
What I mean is that I cannot find any API specification as well as an example on how to input a database source data to presidio analyzer/anonymizer. 
May be it is a limit of me, but I believe it could help many people.
Thank you in advance

**Comment by omri374** [comment]
Hi @dante1119,
Which database are you looking into inputting as a data source?

In order to have Presidio run on a source database, the configuration of both the database and a scheduled job is needed. 
This tutorial explains how to schedule jobs to run on a source database. If any additional information is needed, we'd be happy to help:

https://github.com/microsoft/presidio/blob/master/docs/tutorial_scheduler.md

**Comment by omri374** [comment]
Related to #229

**Comment by SatyaBhagat** [comment]
Hi Omri,

I created the json file with all the required information and attributes, May I know how to execute the above json with the presidio-analyser.

Thank You

**Comment by SatyaBhagat** [comment]
Hi Omri, @omri374 

I created the json file with all the required information and attributes, May I know how to execute the above json with the presidio-analyser.

Thank You

**Comment by navalev** [comment]
You can call the API from any source, can defintly be called as a step in ETL process.
If there are no further questions I will close this issue. We can re-open if needed.
