### ISSUE TITLE
Consider using Black instead of Pylint for Python linting

### ISSUE THREAD

**Issue by omri374** [microsoft/presidio#317]
Black is a new code formatter for python with additional capabilities. It integrates with different IDEs like PyCharm and VSCode.

Black repo: https://github.com/psf/black
Black playground: https://black.now.sh/

PyCharm integration: https://github.com/psf/black#pycharmintellij-idea

VSCode integration:
https://code.visualstudio.com/docs/python/editing#_formatting

Pros: 
- Better formatting and linting capabilities
- More modern (e.g. recommended line width is not 80)

Cons:
- Cumbersome support in some IDEs (e.g. PyCharm)
- Requires refactoring of current code base

**Comment by omri374** [comment]
@dhpollack Feel free to add your thoughts here about your experience with Black

**Comment by dhpollack** [comment]
First off, it should be noted that it's replacing pylint + flake8 with black + flake8.  Black is only a formatter that makes your code pass the linter.

I find the consistency of the formatting to be really nice.  Small things like always using double quotes and formatting lists are opinionated, but I quickly got used to their style.  I always felt like the score that pylint gives is a bit contrived and I end up spending as much time trying to format my code to get a 10.0/10.0 as I did actually writing the code in the first place.  Then I'd add a single parameter to a function and it'd all go to hell again.  All that is replaced by running a single cli command.  Lastly, I feel like there is a lot of overlap between flake8 and pylint, but neither of them by themselves is enough.  Getting rid of one of them, you don't lose much especially since black auto-formats a lot of the complaints anyway. 

The problem with using pylint and black is that black's opinionated formatting isn't compatible with pylint's defaults.  So pylint will complain about files that have been formatted with black.  

The one thing you lose with dropping pylint is imports checking.  A lot of projects use black + flake8 + isort (isort is already in the `Pipfile.lock`) to organize imports.  This is the only downside I can think of by dropping pylint.

**Comment by omri374** [comment]
FYI, most (if not all) of the code is formatted using Black. Recommended pre-commit hooks use black to auto-format.
