### ISSUE TITLE
Switch from Re2 to Hyperscan?

### ISSUE THREAD

**Issue by diwu1989** [microsoft/presidio#344]
Since for each blob of text, multiple regex will be applied. This seems like a use-case better suited for Hyperscan.
https://python-hyperscan.readthedocs.io/en/latest/usage/

Is it easy to fit batch regex evaluation into the current architecture?

**Comment by omri374** [comment]
Hi @diwu1989, thanks for the suggestion!
Switching from RE2 to hyperscan would require a significant architecture change of how Presidio's PII recognizers are currently set up and orchestrated.
In addition, we support non-regex recognizers as well, which should also be refactored in case of such change.

Since we didn't encounter a major performance hit with re2 (most of the latency comes from the NLP work), we currently don't see a need to perform such change.
