### ISSUE TITLE
Missing documentation for context words

### ISSUE THREAD

**Issue by schudoku** [microsoft/presidio#761]
I don´t know how exactly the context words are used to boost the score of a pii finding.

1) Do the words need to be defined exactly or should I define lemmas of the words that I want to match? In the code I see that not the original words/tokens of a sentences are compared to the context words, but the lemmas/keywords of the original words. 
2) How many words before and after a pii finding are taken into consideration? Do punctuation characters count, too?

An improved documentation would help me to improve my accuracy. The lemma question is of special interest for non English languages.

**Comment by omri374** [comment]
Hi @schudoku,
The context words detection in Presidio is a simple rule-based match of the each surrounding word's lemma and the list of keywords configured in the recognizer.
High level pseudocode:
1. Tokenize input text and extract lemmas for each token ([see code here](https://github.com/microsoft/presidio/blob/b8d76c6a7e0a66fcfabcfe1dffd46f8010af2d28/presidio-analyzer/presidio_analyzer/nlp_engine/spacy_nlp_engine.py#L44)).
2. Remove stopwords, punctuations and some other types of tokens ([see code here](https://github.com/microsoft/presidio/blob/b8d76c6a7e0a66fcfabcfe1dffd46f8010af2d28/presidio-analyzer/presidio_analyzer/nlp_engine/nlp_artifacts.py#L31)).
3. Compare N tokens before and after the entity with each term provided in the recognizer's context list ([see code here](https://github.com/microsoft/presidio/blob/b8d76c6a7e0a66fcfabcfe1dffd46f8010af2d28/presidio-analyzer/presidio_analyzer/entity_recognizer.py#L195)).
4. If at least one token was found to match, increase detection confidence ([see code here](https://github.com/microsoft/presidio/blob/b8d76c6a7e0a66fcfabcfe1dffd46f8010af2d28/presidio-analyzer/presidio_analyzer/entity_recognizer.py#L177)).

**Additional information:**
1. The default number of words before and after are 5 for before and 0 for after. This can be changed by setting up the `CONTEXT_PREFIX_COUNT` and `CONTEXT_SUFFIX_COUNT` fields in the recognizer class. For example:
    ```python
    zipcode_recognizer = PatternRecognizer(supported_entity="US_ZIP_CODE", 
                                           patterns = [zipcode_pattern],
                                           context= ["zip", "zipcode"])
    zipcode_recognizer.CONTEXT_PREFIX_COUNT = 10
    zipcode_recognizer.CONTEXT_SUFFIX_COUNT= 10
    ```

2. Presidio uses spaCy's pipelines by default, and lemmas are extracted using spaCy logic and depends of the type of model and pipeline you are using. For more information on lemmatization in spaCy [see this tutorial](https://spacy.io/usage/linguistic-features#lemmatization). spaCy does cover lemmatization for languages other than English. There are multiple ways to extract lemmas in spaCy, one of them is downloading [this package](https://github.com/explosion/spacy-lookups-data) in parallel to spaCy's.

**Limitations with the current approach:**
1. Working with lemmas could be tricky due to lemmas missing for some words or other complexities
2. Having one or more detected context lemmas results in the same boost to performance.
3. Multi-token context phrases are not supported
4. Some context words could be useful for multiple PII entity recognizers (for example "number"). Adding such general context words would increase the number of false positives especially for non-specific PII recognizers.


The context detection mechanism used in Presidio is very simple. If you have any thoughts on improving it, or even better, would like to propose a change, we would be very interested to know. This is an interesting problem to solve and could be very useful for improving the detection rates across the entire solution.

**Comment by schudoku** [comment]
Hi @omri374,

thank you for your detailed explanation. Its indeed a simple mechanism but also a very useful one :) As I understand the architecture there is always the possibility to create a new entitiy recognizer and do some magic with the nlp artefacts provided by the nlp engine or to even create something from scratch. The possibility to specify CONTEXT_PREFIX_COUNT and CONTEXT_SUFFIX_COUNT without modifying the code comes in handy to test different values easily. Thank you!

**Comment by hummingbird1989** [comment]
@schudoku @omri374 how would I include context words in suffixes? 
I tried this 

> EntityRecognizer.CONTEXT_PREFIX_COUNT = 10
> EntityRecognizer.CONTEXT_SUFFIX_COUNT= 10

but it didn't seem to have worked. Is there anything I need to do after setting those values?

**Comment by omri374** [comment]
Hi @hummingbird1989, this way is deprecated. Please see https://microsoft.github.io/presidio/tutorial/06_context/

**Comment by hummingbird1989** [comment]
@omri374 Thanks for the link. Are context words considered both **before** and **after** the pattern?

**Comment by omri374** [comment]
In `LemmaContextAwareEnhancer` you can define how many tokens before and after are considered:
```python
from presidio_analyzer import AnalyzerEngine
from presidio_analyzer.context_aware_enhancers import LemmaContextAwareEnhancer

context_enhancer = LemmaContextAwareEnhancer(context_similarity_factor=0.45, 
                                             min_score_with_context_similarity=0.4,
                                             context_prefix_count=5,
                                             context_suffix_count=5)

analyzer = AnalyzerEngine(context_aware_enhancer=context_enhancer)
```
