### ISSUE TITLE
Can keyword list contain phrases?

### ISSUE THREAD

**Issue by hummingbird1989** [microsoft/presidio#901]
Let's say I want to build my own US SSN detector that is built to detect the 3-2-4 format with context words
If my keywords are actually phrases like "social security", can those be added to `context_words`?

**Comment by omri374** [comment]
Hi @hummingbird1989. The context mechanism can be extended to support additional types of logic. The default one ([`LemmaContextAwareEnhancer`](https://github.com/microsoft/presidio/blob/main/presidio-analyzer/presidio_analyzer/context_aware_enhancers/lemma_context_aware_enhancer.py)) uses lemma, but one can create a new one which inherits from [`ContextAwareEnhancer`](https://github.com/microsoft/presidio/blob/main/presidio-analyzer/presidio_analyzer/context_aware_enhancers/context_aware_enhancer.py).

I would suggest going over the logic in the Lemma context aware enhancer and seeing what needs to be adapted to uses phrases (e.g., by doing a lookup of a substring before and after an entity).

The `enhance_using_context` method is the one that probably needs an update:
https://github.com/microsoft/presidio/blob/fb01d2374ebef9b0b1e809790e49a75e02d731cb/presidio-analyzer/presidio_analyzer/context_aware_enhancers/lemma_context_aware_enhancer.py#L43


Once you have your new enhancer, you can plug it instead of the lemma one. For example:

```python
class MyContextAwareEnhancer(ContextAwareEnhancer):
    #TODO: implement methods
    pass


my_context_aware_enhancer = MyContextAwareEnhancer(...)

analyzer = AnalyzerEngine(context_aware_enhancer=my_context_aware_enhancer)
analyzer.analyze(...)
```

Hope this helps!

**Comment by hummingbird1989** [comment]
@omri374 Thanks for the detailed answer. I'm getting some strange behavior when trying to add multiple `PatternRecognizer`s. The code below is based on the link [here](https://microsoft.github.io/presidio/tutorial/06_context/)
```
from presidio_analyzer import (
    Pattern,
    PatternRecognizer,
    RecognizerRegistry,
    AnalyzerEngine,
)

# Define the regex pattern
regex = r"(\b\d{5}(?:\-\d{4})?\b)"  # very weak regex pattern
zipcode_pattern = Pattern(name="zip code (weak)", regex=regex, score=0.01)

# Define the recognizer with the defined pattern
zipcode_recognizer = PatternRecognizer(
    supported_entity="US_ZIP_CODE", patterns=[zipcode_pattern]
)

zipcode_recognizer_w_context = PatternRecognizer(
    supported_entity="US_ZIP_CODE_PATTERN",
    patterns=[zipcode_pattern],
    context=["zip", "zipcode"],
)
registry = RecognizerRegistry()
registry.add_recognizer(zipcode_recognizer)
registry.add_recognizer(zipcode_recognizer_w_context)
analyzer = AnalyzerEngine(registry=registry)

# Test
results = analyzer.analyze(text="My zip code is 90210", language="en")

print(f"Result:\n {results}")
```

The output is as follows:
` [type: US_ZIP_CODE_PATTERN, start: 15, end: 20, score: 0.75, type: US_ZIP_CODE, start: 15, end: 20, score: 0.75]`

If I understand the example correctly, shouldn't I get two results with scores 0.4 and 0.01 respectively? I get those scores when only one of the recognizers is added

**Comment by omri374** [comment]
Looks like a duplicate of #889. Let's continue the discussion there.
